project_id = "bbhahwkstilfvcitjhqo"

[functions.process-notifications]
verify_jwt = false

[functions.create-subscription]
verify_jwt = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.confirm-subscription]
verify_jwt = true

[functions.export-applications]
verify_jwt = true
